name: skdownscale
channels:
  - conda-forge
dependencies:
  - pangeo-notebook
  - pandas
  - xarray
  - seaborn
  - mpl-probscale
  - matplotlib
  - scipy
  - numpy
  - scikit-learn
  - dask
  - distributed
  - pydap
  - docopt
  - zarr
  - netcdf4
  - intake-esm
  - gcsfs
  - pip
  - pip:
    - git+https://github.com/pydata/xarray.git@e8bd8665e8fd762031c2d9c87987d21e113e41cc
    - git+https://github.com/jhamman/scikit-downscale.git@1d451a5d12473dd50bc8d979b98078db9392b3f0
